"""CLI contracts for locating Playbook agent runs in OMP session transcripts."""

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


COLLECTOR = Path(__file__).resolve().parents[1] / "scripts" / "collect-agent-runs.py"
MARKER = "<!-- GENERATED BY scripts/build-skills.py; DO NOT EDIT. -->"
AGENT = "review-prompt-agent"


def entry(role, content, **extra):
    return {"type": "message", "message": {"role": role, "content": content, **extra}}


def init(agent, timestamp):
    return {"type": "session_init", "agent": agent, "timestamp": timestamp,
            "resolvedModel": "provider/model", "systemPrompt": "prompt"}


def dispatch(name, agent=AGENT):
    return entry("assistant", [{"type": "toolCall", "name": "task",
                                "arguments": {"tasks": [{"name": name, "agent": agent, "task": "t"}]}}])


def skill_read():
    return entry("toolResult", [{"type": "text", "text": MARKER + "\n# Skill"}], toolName="read")


class CollectAgentRunsTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="playbook runs ")
        self.addCleanup(temporary.cleanup)
        self.sessions = Path(temporary.name)

    def write(self, relative, entries):
        path = self.sessions / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("".join(json.dumps(item) + "\n" for item in entries), encoding="utf-8")
        return path

    def run_collector(self, *args):
        return subprocess.run([sys.executable, str(COLLECTOR), "--sessions", str(self.sessions), *args],
                              capture_output=True, text=True, check=False)

    def collect(self, *args):
        result = self.run_collector(*args)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stderr, "")
        return json.loads(result.stdout)

    def seed(self):
        main = self.write("-work-app/2026-09-20_a.jsonl", [
            {"type": "session", "cwd": "/work/app"},
            entry("user", "Review the prompt"),
            dispatch("Other", agent="task"),
            dispatch("Rev1"),
            entry("toolResult", [{"type": "text", "text": "Spawned Rev1"}], toolName="task"),
            entry("toolResult", [{"type": "text", "text":
                  '<task-result id="Other">done</task-result>\nStill running: Rev1'}], toolName="wait"),
            {"type": "custom_message", "customType": "async-result",
             "content": '<task-result id="Rev1" agent="review-prompt-agent">done</task-result>'},
            entry("assistant", [{"type": "text", "text": "Rev1 found two issues."}]),
            entry("user", "The second Rev1 finding is wrong."),
        ])
        folder = main.with_suffix("")
        rev1 = self.write(f"-work-app/{folder.name}/Rev1.jsonl", [
            {"type": "session", "cwd": "/work/app"},
            init(AGENT, "2026-09-20T01:00:00Z"),
            entry("user", "Review the EXPORT prompt"),
            skill_read(),
            entry("assistant", [{"type": "text", "text": "Draft"}], stopReason="toolUse"),
            dispatch("Child"),
            entry("assistant", [{"type": "text", "text": "Report\n- **Friction:** skill link was unreadable"}],
                  stopReason="stop"),
        ])
        self.write(f"-work-app/{folder.name}/Other.jsonl", [init("task", "2026-09-20T01:00:00Z")])
        self.write(f"-work-app/{folder.name}/Late.jsonl", [init(AGENT, "2026-10-05T00:00:00Z")])
        child = self.write(f"-work-app/{folder.name}/Rev1/Rev1.Child.jsonl", [
            init(AGENT, "2026-09-20T02:00:00Z"),
            entry("assistant", [{"type": "text", "text": "Nested report"}], stopReason="aborted"),
        ])
        child.with_suffix(".md").write_text("# Nested\n\nFriction: tool rejected an absolute path\n",
                                            encoding="utf-8")
        self.write("-other/2026-09-21_b.jsonl", [{"type": "session", "cwd": "/work/other"}])
        self.write("-other/2026-09-21_b/Rev2.jsonl", [init(AGENT, "2026-09-21T00:00:00Z")])
        self.write("-sub/2026-09-22_c.jsonl", [{"type": "session", "cwd": "/work/app/.worktrees/t1"}])
        self.write("-sub/2026-09-22_c/Rev3.jsonl", [init(AGENT, "2026-09-22T00:00:00Z")])
        return main, rev1, child

    def test_points_to_each_run_its_parent_reaction_and_friction(self):
        main, rev1, child = self.seed()
        report = self.collect("--agent", AGENT, "--since", "2026-09-20", "--until", "2026-09-30")
        runs = {run["run"]: run for run in report["runs"]}
        self.assertEqual(sorted(runs), ["Child", "Rev1", "Rev2", "Rev3"])
        self.assertEqual(report["until"], "2026-09-30T23:59:59.999999+00:00")

        rev = runs["Rev1"]
        self.assertEqual(rev["project"], "/work/app")
        self.assertEqual(rev["model"], "provider/model")
        self.assertEqual(rev["transcript"], {"path": str(rev1), "lines": 7, "initLine": 2, "taskLine": 3,
                                             "skillReadLine": 4, "finalLine": 7, "endReason": "stop"})
        self.assertIsNone(rev["output"])
        self.assertEqual(rev["friction"], [{"path": str(rev1), "line": 7, "text": "skill link was unreadable"}])
        self.assertEqual(rev["parent"], {"path": str(main), "dispatchLine": 4, "resultLine": 7,
                                         "developerReplyLine": 9})

        nested = runs["Child"]
        self.assertEqual(nested["parent"]["path"], str(rev1))
        self.assertEqual(nested["parent"]["dispatchLine"], 6)
        self.assertIsNone(nested["parent"]["resultLine"])
        self.assertIsNone(nested["transcript"]["skillReadLine"])
        self.assertIsNone(nested["transcript"]["taskLine"])
        self.assertEqual(nested["transcript"]["endReason"], "aborted")
        self.assertEqual(nested["output"], str(child.with_suffix(".md")))
        self.assertEqual(nested["friction"], [{"path": str(child.with_suffix(".md")), "line": 3,
                                               "text": "tool rejected an absolute path"}])

    def test_window_and_project_filters(self):
        self.seed()
        unbounded = self.collect("--agent", AGENT, "--since", "2026-09-20T01:30:00Z")
        self.assertIsNone(unbounded["until"])
        self.assertEqual([run["run"] for run in unbounded["runs"]], ["Child", "Rev2", "Rev3", "Late"])

        scoped = self.collect("--agent", AGENT, "--since", "2026-09-01", "--until", "2026-09-30",
                              "--project", "/work/app/")
        self.assertEqual(scoped["project"], "/work/app")
        self.assertEqual([run["run"] for run in scoped["runs"]], ["Rev1", "Child", "Rev3"])
        self.assertEqual(self.collect("--agent", AGENT, "--since", "2026-09-01",
                                      "--project", "/work/ap")["runs"], [])

    def test_rejects_invalid_arguments_without_output(self):
        self.seed()
        cases = [
            (["--agent", "task", "--since", "2026-09-01"], "unknown Playbook agent 'task'"),
            (["--agent", AGENT, "--since", "yesterday"], "invalid date or timestamp: 'yesterday'"),
            (["--agent", AGENT, "--since", "2026-09-02", "--until", "2026-09-01"],
             "--since must not be after --until"),
            (["--agent", AGENT, "--since", "2026-09-01", "--project", "work/app"],
             "--project must be an absolute path"),
            (["--agent", AGENT, "--since", "2026-09-01", "--sessions", str(self.sessions / "missing")],
             "sessions directory not found"),
        ]
        for args, message in cases:
            with self.subTest(args=args):
                result = self.run_collector(*args)
                self.assertEqual(result.returncode, 1)
                self.assertEqual(result.stdout, "")
                self.assertIn(message, result.stderr)


if __name__ == "__main__":
    unittest.main()
