"""Consumer-visible safety and inclusion contracts for the optional publisher."""

import json
import runpy
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


PUBLISHER = Path(__file__).resolve().parents[1] / "scripts" / "build-prompts.py"
PUBLISHER_VALUES = runpy.run_path(str(PUBLISHER))
SKILL_POINTER = PUBLISHER_VALUES["SKILL_POINTER"]
COMPLETION_LINE = PUBLISHER_VALUES["COMPLETION_LINE"]
FALLBACK_LINE = PUBLISHER_VALUES["FALLBACK_LINE"]


class BuildPromptsTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="playbook publisher ")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        for directory in ("agents", "scripts", "guides", "prompts"):
            (self.root / directory).mkdir()
        shutil.copy2(PUBLISHER, self.root / "scripts" / PUBLISHER.name)
        self.rules = self.root / "guides" / "rules.md"
        self.rules.write_text(
            "# Guide\n\n## Parent\nPreserve the parent obligation.\n\n"
            "### Child\nPreserve the child obligation.\n\n"
            "### Sibling\nPreserve the sibling obligation.\n",
            encoding="utf-8",
        )
        (self.root / "prompts" / "task.md").write_text(
            "# Task\n\n## Required guidance\n\n"
            "- [Child](../guides/rules.md#child)\n"
            "- [Parent](../guides/rules.md#parent)\n"
            "- [Child again](../guides/rules.md#child)\n\n"
            "## Instructions\nApply the supplied obligations.\n",
            encoding="utf-8",
        )
        self.output = self.root / "skills" / "task" / "SKILL.md"
        self.agent = self.root / "agents" / "task-agent.md"
        self.write_agent()
        self.write_checks()

    def write_agent(
        self,
        *,
        path=None,
        name="task-agent",
        skill="task",
        tools="read",
        omit_standard=None,
        extra_body="",
    ):
        path = path or self.agent
        standard = [
            SKILL_POINTER.format(skill=skill),
            COMPLETION_LINE,
            FALLBACK_LINE.format(skill=skill),
        ]
        body = [
            "You handle exactly one test task.",
            *[line for line in standard if line != omit_standard],
        ]
        if extra_body:
            body.append(extra_body)
        path.write_text(
            "---\n"
            + "name: "
            + name
            + "\n"
            + 'description: "Test agent"\n'
            + "model: test/model\n"
            + "tools: "
            + tools
            + "\n"
            + "autoloadSkills:\n"
            + "  - "
            + skill
            + "\n"
            + "---\n\n"
            + "\n\n".join(body)
            + "\n",
            encoding="utf-8",
        )

    def write_checks(self, *, skills_without_agents=None, exemptions=None):
        configuration = {
            "skillsWithoutAgents": skills_without_agents or {},
            "exemptions": exemptions or {},
        }
        (self.root / "agents" / "checks.json").write_text(
            json.dumps(configuration), encoding="utf-8"
        )

    def publish_current(self):
        result = self.publish()
        self.assertEqual(result.returncode, 0, result.stderr)
        return result

    def publish(self, *arguments):
        return subprocess.run(
            [sys.executable, str(self.root / "scripts" / PUBLISHER.name), *arguments],
            cwd=self.root.parent,
            text=True,
            capture_output=True,
            check=False,
        )

    def test_publishes_self_contained_skill_with_frontmatter(self):
        result = self.publish()
        self.assertEqual(result.returncode, 0, result.stderr)
        lines = self.output.read_text(encoding="utf-8").splitlines()
        self.assertEqual(lines[0], "---")
        self.assertEqual(lines[1], "name: task")
        self.assertTrue(lines[2].startswith("description: "))
        self.assertNotEqual(lines[2], 'description: ""')
        self.assertEqual(lines[3], "hide: true")
        self.assertEqual(lines[4], "---")
        self.assertEqual(
            lines[5], "<!-- GENERATED BY scripts/build-prompts.py; DO NOT EDIT. -->"
        )
        content = "\n".join(lines[6:])
        self.assertIn("## Included guidance", content)
        self.assertIn("Preserve the parent obligation.", content)
        self.assertIn("## Task", content)
        self.assertIn("# Task", content)
        self.assertIn("Apply the supplied obligations.", content)
        self.assertIn("## Supply inputs", content)

    def test_parent_after_child_preserves_all_rules_once(self):
        result = self.publish()
        self.assertEqual(result.returncode, 0, result.stderr)
        content = self.output.read_text(encoding="utf-8")
        for obligation in ("parent", "child", "sibling"):
            self.assertEqual(content.count("Preserve the " + obligation + " obligation."), 1)

    def test_freshness_check_detects_changed_guidance_without_writing(self):
        result = self.publish()
        self.assertEqual(result.returncode, 0, result.stderr)
        previous = self.output.read_bytes()
        self.rules.write_text(self.rules.read_text(encoding="utf-8") + "\nA new obligation.\n", encoding="utf-8")
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertEqual(self.output.read_bytes(), previous)
        result = self.publish()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("A new obligation.", self.output.read_text(encoding="utf-8"))
        self.assertEqual(self.publish("--check").returncode, 0)

    def test_unrecognized_output_is_not_overwritten(self):
        self.output.parent.mkdir(parents=True)
        user_content = "These are independently maintained user instructions.\n"
        self.output.write_text(user_content, encoding="utf-8")
        result = self.publish()
        self.assertEqual(result.returncode, 1)
        self.assertEqual(self.output.read_text(encoding="utf-8"), user_content)

    def test_agent_check_accepts_a_passing_agent(self):
        self.publish_current()
        result = self.publish("--check")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_skill_has_agent_rule_fails(self):
        self.publish_current()
        self.agent.unlink()
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("skill task: skill-has-agent:", result.stderr)

    def test_agent_has_skill_rule_fails(self):
        self.publish_current()
        self.write_agent(skill="missing")
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("agent task-agent.md: agent-has-skill:", result.stderr)

    def test_name_matches_file_rule_fails(self):
        self.publish_current()
        self.write_agent(name="different-agent")
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("agent task-agent.md: name-matches-file:", result.stderr)

    def test_standard_lines_rule_fails(self):
        self.publish_current()
        self.write_agent(omit_standard=COMPLETION_LINE)
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("agent task-agent.md: standard-lines:", result.stderr)

    def test_no_done_when_rule_fails(self):
        self.publish_current()
        self.write_agent(extra_body="You are done when the work is complete.")
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("agent task-agent.md: no-done-when:", result.stderr)

    def test_reviewer_read_only_rule_fails(self):
        self.publish_current()
        self.agent.unlink()
        self.agent = self.root / "agents" / "review-task-agent.md"
        self.write_agent(name="review-task-agent", tools="read, write")
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("agent review-task-agent.md: reviewer-read-only:", result.stderr)

    def test_valid_exception_suppresses_agent_rule(self):
        self.publish_current()
        self.agent.unlink()
        self.agent = self.root / "agents" / "review-task-agent.md"
        self.write_agent(name="review-task-agent", tools="read, write")
        self.write_checks(
            exemptions={
                "review-task-agent": {
                    "reviewer-read-only": "This fixture exercises the exception."
                }
            }
        )
        result = self.publish("--check")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_skills_without_agents_suppresses_skill_rule(self):
        self.publish_current()
        self.agent.unlink()
        self.write_checks(
            skills_without_agents={
                "task": "This fixture exercises a directly loaded skill."
            }
        )
        result = self.publish("--check")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_exception_with_empty_reason_fails(self):
        self.publish_current()
        self.write_checks(
            exemptions={"task-agent": {"standard-lines": ""}}
        )
        result = self.publish("--check")
        self.assertEqual(result.returncode, 1)
        self.assertIn("reason must be a non-empty string", result.stderr)

    def test_exception_naming_missing_agent_skill_or_rule_fails(self):
        self.publish_current()
        cases = (
            (
                {},
                {"missing-agent": {"standard-lines": "A reason."}},
                "unknown agent",
            ),
            ({"missing-skill": "A reason."}, {}, "unknown skill"),
            (
                {},
                {"task-agent": {"missing-rule": "A reason."}},
                "unknown rule",
            ),
        )
        for skills_without_agents, exemptions, expected in cases:
            with self.subTest(expected=expected):
                self.write_checks(
                    skills_without_agents=skills_without_agents,
                    exemptions=exemptions,
                )
                result = self.publish("--check")
                self.assertEqual(result.returncode, 1)
                self.assertIn(expected, result.stderr)


if __name__ == "__main__":
    unittest.main()
