#!/usr/bin/env python3
"""Publish file-aware prompt sources as self-contained chat bundles."""

import argparse
import re
import sys
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple
from urllib.parse import unquote


GENERATED_MARKER = "<!-- GENERATED BY scripts/build-prompts.py; DO NOT EDIT. -->"
FENCE_OPEN = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})(?:[^\n]*)$")
ATX_HEADING = re.compile(r"^[ \t]{0,3}(#{1,6})(?:[ \t]+|$)(.*?)(?:\r?\n)?$")
SETEXT_UNDERLINE = re.compile(r"^[ \t]{0,3}(=+|-+)[ \t]*(?:\r?\n)?$")
MANIFEST_ITEM = re.compile(r"^[ \t]*[-*+][ \t]+\[([^\]]+)\]\(([^()\s]+)\)[ \t]*(?:\r?\n)?$")
URL_SCHEME = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")


class BuildError(Exception):
    """An invalid source or unsafe output condition."""


@dataclass(frozen=True)
class Heading:
    level: int
    title: str
    slug: str
    start: int
    end: int


@dataclass
class Document:
    path: Path
    relative_path: Path
    lines: List[str]
    headings: List[Heading]


@dataclass(frozen=True)
class SelectedSection:
    document: Document
    start: int
    end: int
    heading_index: Optional[int]

    @property
    def is_whole_document(self) -> bool:
        return self.heading_index is None


@dataclass(frozen=True)
class Bundle:
    source: Path
    output: Path
    content: bytes


def repository_root() -> Path:
    return Path(__file__).resolve().parent.parent


def is_fence_open(line: str) -> Optional[Tuple[str, int]]:
    match = FENCE_OPEN.match(line)
    if not match:
        return None
    marker = match.group(1)
    return marker[0], len(marker)


def is_fence_close(line: str, marker: str, length: int) -> bool:
    return bool(
        re.match(
            r"^[ \t]{0,3}" + re.escape(marker) + r"{" + str(length) + r",}[ \t]*(?:\r?\n)?$",
            line,
        )
    )


def heading_slug(title: str) -> str:
    """Match the simple GitHub-style slugs used by this repository's headings."""
    normalized = unicodedata.normalize("NFKD", title).lower()
    filtered = "".join(
        character
        for character in normalized
        if character.isalnum() or character in " _-" or character.isspace()
    )
    return re.sub(r"\s+", "-", filtered.strip()).strip("-")


def parse_headings(lines: Sequence[str]) -> List[Heading]:
    raw_headings: List[Tuple[int, str, int]] = []
    in_fence = False
    fence_marker = ""
    fence_length = 0

    for index, line in enumerate(lines):
        if in_fence:
            if is_fence_close(line, fence_marker, fence_length):
                in_fence = False
            continue

        opening = is_fence_open(line)
        if opening:
            fence_marker, fence_length = opening
            in_fence = True
            continue

        atx = ATX_HEADING.match(line)
        if atx:
            title = re.sub(r"[ \t]+#+[ \t]*$", "", atx.group(2)).strip()
            raw_headings.append((len(atx.group(1)), title, index))
            continue

        # Setext headings are supported as well. The conservative exclusions avoid
        # treating list items and block quotes followed by a rule as headings.
        if index + 1 < len(lines):
            underline = SETEXT_UNDERLINE.match(lines[index + 1])
            candidate = line.strip()
            if (
                underline
                and candidate
                and not candidate.startswith((">", "- ", "* ", "+ "))
                and not line.startswith(("    ", "\t"))
            ):
                raw_headings.append((1 if underline.group(1)[0] == "=" else 2, candidate, index))

    counts: Dict[str, int] = {}
    headings: List[Heading] = []
    for position, (level, title, start) in enumerate(raw_headings):
        base_slug = heading_slug(title) or "heading-" + str(start + 1)
        occurrence = counts.get(base_slug, 0)
        counts[base_slug] = occurrence + 1
        slug = base_slug if occurrence == 0 else base_slug + "-" + str(occurrence)
        end = len(lines)
        for next_level, _, next_start in raw_headings[position + 1 :]:
            if next_level <= level:
                end = next_start
                break
        headings.append(Heading(level, title, slug, start, end))
    return headings


def is_inside(root: Path, candidate: Path) -> bool:
    try:
        candidate.relative_to(root)
        return True
    except ValueError:
        return False


def load_document(root: Path, path: Path, cache: Dict[Path, Document]) -> Document:
    resolved = path.resolve()
    if not is_inside(root, resolved):
        raise BuildError("local source escapes repository: " + str(path))
    if resolved in cache:
        return cache[resolved]
    if not resolved.is_file():
        raise BuildError("referenced Markdown file does not exist: " + str(path))
    try:
        text = resolved.read_text(encoding="utf-8")
    except UnicodeDecodeError as error:
        raise BuildError("source is not UTF-8: " + str(path)) from error
    document = Document(
        path=resolved,
        relative_path=resolved.relative_to(root),
        lines=text.splitlines(keepends=True),
        headings=parse_headings(text.splitlines(keepends=True)),
    )
    cache[resolved] = document
    return document


def local_path(root: Path, current: Document, path_text: str) -> Path:
    if not path_text:
        return current.path
    decoded = unquote(path_text)
    if "\\" in decoded or "\x00" in decoded:
        raise BuildError("malformed local link in " + str(current.relative_path) + ": " + path_text)
    candidate = Path(decoded)
    if candidate.is_absolute():
        raise BuildError("local link escapes repository in " + str(current.relative_path) + ": " + path_text)
    resolved = (current.path.parent / candidate).resolve()
    if not is_inside(root, resolved):
        raise BuildError("local link escapes repository in " + str(current.relative_path) + ": " + path_text)
    return resolved


def find_required_guidance(document: Document) -> Heading:
    matching = [heading for heading in document.headings if heading.title == "Required guidance"]
    if len(matching) != 1 or matching[0].level != 2:
        raise BuildError(
            str(document.relative_path)
            + " must contain exactly one level-two 'Required guidance' heading"
        )
    return matching[0]


def manifest_sections(
    root: Path,
    source: Document,
    required: Heading,
    cache: Dict[Path, Document],
) -> List[SelectedSection]:
    selections: List[SelectedSection] = []
    entries = 0


    for index in range(required.start + 1, required.end):
        line = source.lines[index]
        if not line.strip():
            continue
        item = MANIFEST_ITEM.match(line)
        if not item:
            raise BuildError(
                "malformed Required guidance entry in "
                + str(source.relative_path)
                + " at line "
                + str(index + 1)
            )
        entries += 1

        target = item.group(2)
        if target.startswith("<") or "?" in target or URL_SCHEME.match(target) or target.startswith("//"):
            raise BuildError(
                "Required guidance must use a relative local Markdown link in "
                + str(source.relative_path)
                + " at line "
                + str(index + 1)
            )
        path_text, separator, fragment = target.partition("#")
        if not path_text or not path_text.lower().endswith(".md") or (separator and not fragment):
            raise BuildError(
                "malformed Required guidance link in "
                + str(source.relative_path)
                + " at line "
                + str(index + 1)
            )
        target_path = local_path(root, source, path_text)
        document = load_document(root, target_path, cache)

        heading_index: Optional[int] = None
        if separator:
            requested_slug = unquote(fragment)
            matches = [
                position
                for position, heading in enumerate(document.headings)
                if heading.slug == requested_slug
            ]
            if len(matches) != 1:
                raise BuildError(
                    "Required guidance fragment does not name a heading in "
                    + str(document.relative_path)
                    + ": #"
                    + fragment
                )
            heading_index = matches[0]
            heading = document.headings[heading_index]
            candidate = SelectedSection(document, heading.start, heading.end, heading_index)
        else:
            candidate = SelectedSection(document, 0, len(document.lines), None)

        overlapping = [
            position
            for position, selected in enumerate(selections)
            if selected.document.path == document.path
            and candidate.start < selected.end
            and selected.start < candidate.end
        ]
        if any(
            selections[position].start <= candidate.start
            and candidate.end <= selections[position].end
            and (selections[position].is_whole_document or not candidate.is_whole_document)
            for position in overlapping
        ):
            continue
        if overlapping:
            # Heading ranges are nested: a later parent replaces its children
            # at their first position, retaining the parent's remaining rules.
            insertion = overlapping[0]
            selections = [
                selected for position, selected in enumerate(selections)
                if position not in overlapping
            ]
            selections.insert(insertion, candidate)
        else:
            selections.append(candidate)

    if not entries:
        raise BuildError(str(source.relative_path) + " must list at least one Required guidance link")
    return selections


def included_sections(selections: Iterable[SelectedSection]) -> Dict[Tuple[Path, Optional[str]], str]:
    sections: Dict[Tuple[Path, Optional[str]], str] = {}
    for selection in selections:
        document = selection.document
        if selection.is_whole_document:
            sections[(document.path, None)] = (
                document.headings[0].title if document.headings else document.relative_path.as_posix()
            )
        for heading in document.headings:
            if selection.start <= heading.start < selection.end:
                sections[(document.path, heading.slug)] = heading.title
    return sections


def split_destination(destination: str) -> str:
    """Return a Markdown link destination without its optional title."""
    value = destination.strip()
    if value.startswith("<"):
        closing = value.find(">")
        if closing == -1:
            return value
        return value[1:closing]
    for index, character in enumerate(value):
        if character.isspace():
            return value[:index]
    return value




def rewrite_destination(
    root: Path,
    current: Document,
    destination: str,
    sections: Dict[Tuple[Path, Optional[str]], str],
) -> Optional[str]:
    target_text = split_destination(destination)
    if not target_text:
        return None
    if URL_SCHEME.match(target_text) and not target_text.lower().startswith("file:"):
        return None
    if target_text.startswith("//"):
        return None
    if target_text.lower().startswith("file:"):
        raise BuildError("file URL is not allowed in " + str(current.relative_path) + ": " + target_text)

    path_text, separator, fragment = target_text.partition("#")
    target = local_path(root, current, path_text)
    decoded_fragment = unquote(fragment) if separator else None
    section = sections.get((target, decoded_fragment))
    if section:
        return "section:" + section
    reference = target.relative_to(root).as_posix()
    if fragment:
        reference += "#" + fragment
    return "source:" + reference


def rewrite_links_in_line(
    root: Path,
    current: Document,
    line: str,
    sections: Dict[Tuple[Path, Optional[str]], str],
) -> str:
    result: List[str] = []
    cursor = 0
    while True:
        opening = line.find("[", cursor)
        if opening == -1:
            result.append(line[cursor:])
            break
        close = line.find("]", opening + 1)
        if close == -1 or close + 1 >= len(line) or line[close + 1] != "(":
            result.append(line[cursor : opening + 1])
            cursor = opening + 1
            continue
        depth = 1
        position = close + 2
        while position < len(line) and depth:
            if line[position] == "(":
                depth += 1
            elif line[position] == ")":
                depth -= 1
            position += 1
        if depth:
            result.append(line[cursor : opening + 1])
            cursor = opening + 1
            continue

        start = opening - 1 if opening > 0 and line[opening - 1] == "!" else opening
        label = line[opening + 1 : close]
        destination = line[close + 2 : position - 1]
        rewritten = rewrite_destination(root, current, destination, sections)
        result.append(line[cursor:start])
        if rewritten is None:
            result.append(line[start:position])
        elif rewritten.startswith("section:"):
            result.append(label + ' (see included section "' + rewritten[len("section:") :] + '")')
        else:
            # Local source paths are intentionally text, not broken relative URLs.
            result.append("[" + label + " (source: " + rewritten[len("source:") :] + ")]")
        cursor = position
    return "".join(result)


def rewrite_links(
    root: Path,
    current: Document,
    lines: Sequence[str],
    sections: Dict[Tuple[Path, Optional[str]], str],
) -> str:
    rewritten: List[str] = []
    in_fence = False
    fence_marker = ""
    fence_length = 0
    for line in lines:
        if in_fence:
            rewritten.append(line)
            if is_fence_close(line, fence_marker, fence_length):
                in_fence = False
            continue
        opening = is_fence_open(line)
        if opening:
            rewritten.append(line)
            fence_marker, fence_length = opening
            in_fence = True
            continue
        rewritten.append(rewrite_links_in_line(root, current, line, sections))
    return "".join(rewritten)


def render_section(
    root: Path,
    selection: SelectedSection,
    sections: Dict[Tuple[Path, Optional[str]], str],
) -> str:
    document = selection.document
    return rewrite_links(
        root, document, document.lines[selection.start : selection.end], sections
    ).strip() + "\n"




def render_bundle(root: Path, source: Document, selections: Sequence[SelectedSection]) -> bytes:
    sections = included_sections(selections)
    required = find_required_guidance(source)
    task_lines = source.lines[: required.start] + source.lines[required.end :]
    task = rewrite_links(root, source, task_lines, sections).strip()
    guidance = "\n".join(render_section(root, selection, sections).rstrip() for selection in selections)
    content = "\n".join(
        [
            GENERATED_MARKER,
            "",
            "## Included guidance",
            "",
            guidance,
            "## Task",
            "",
            task,
            "",
            "## Supply inputs",
            "Provide the target, exact revision label, source material, relevant context, and the action-specific request.",
            "",
        ]
    )
    return content.encode("utf-8")


def build_bundles(root: Path) -> List[Bundle]:
    prompts_dir = root / "prompts"
    if not prompts_dir.is_dir():
        raise BuildError("prompt source directory does not exist: " + str(prompts_dir))
    source_paths = sorted(
        path for path in prompts_dir.glob("*.md") if path.name != "README.md" and path.is_file()
    )
    if not source_paths:
        raise BuildError("prompt library is empty: " + str(prompts_dir))

    cache: Dict[Path, Document] = {}
    bundles: List[Bundle] = []
    for path in source_paths:
        source = load_document(root, path, cache)
        required = find_required_guidance(source)
        selections = manifest_sections(root, source, required, cache)
        output = root / "prompts" / "chat" / path.name
        bundles.append(Bundle(path, output, render_bundle(root, source, selections)))
    return bundles


def is_our_bundle(content: bytes) -> bool:
    return content.startswith(GENERATED_MARKER.encode("utf-8") + b"\n")


def inspect_outputs(root: Path, bundles: Sequence[Bundle]) -> Tuple[List[Bundle], List[Path]]:
    chat_dir = root / "prompts" / "chat"
    expected = {bundle.output for bundle in bundles}
    changed: List[Bundle] = []
    stale: List[Path] = []

    if chat_dir.is_symlink():
        raise BuildError("chat bundle path must not be a symbolic link: " + str(chat_dir))
    if chat_dir.exists() and not chat_dir.is_dir():
        raise BuildError("chat bundle path is not a directory: " + str(chat_dir))
    for bundle in bundles:
        if bundle.output.is_symlink():
            raise BuildError("chat bundle output must not be a symbolic link: " + str(bundle.output))
        if not bundle.output.exists():
            changed.append(bundle)
            continue
        if not bundle.output.is_file():
            raise BuildError("chat bundle output is not a file: " + str(bundle.output))
        existing = bundle.output.read_bytes()
        if not is_our_bundle(existing):
            raise BuildError("refusing to overwrite unrecognized file: " + str(bundle.output))
        if existing != bundle.content:
            changed.append(bundle)

    if chat_dir.is_dir():
        for path in sorted(chat_dir.glob("*.md")):
            if path in expected:
                continue
            if path.is_symlink():
                raise BuildError("chat bundle entry must not be a symbolic link: " + str(path))
            if not path.is_file():
                raise BuildError("chat bundle entry is not a file: " + str(path))
            if not is_our_bundle(path.read_bytes()):
                raise BuildError("refusing to delete unrecognized file: " + str(path))
            stale.append(path)
    return changed, stale


def publish(root: Path, check: bool) -> int:
    bundles = build_bundles(root)
    changed, stale = inspect_outputs(root, bundles)
    if check:
        if changed or stale:
            for bundle in changed:
                print("out of date: " + str(bundle.output.relative_to(root)), file=sys.stderr)
            for path in stale:
                print("stale: " + str(path.relative_to(root)), file=sys.stderr)
            return 1
        print("prompt bundles: current")
        return 0

    if changed or stale:
        chat_dir = root / "prompts" / "chat"
        chat_dir.mkdir(exist_ok=True)
        for bundle in changed:
            bundle.output.write_bytes(bundle.content)
        for path in stale:
            path.unlink()
    print("prompt bundles: " + str(len(changed) + len(stale)) + " changed")
    return 0


def parse_arguments(arguments: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated chat bundles are not current")
    return parser.parse_args(arguments)


def main(arguments: Optional[Sequence[str]] = None) -> int:
    try:
        return publish(repository_root(), parse_arguments(arguments).check)
    except (BuildError, OSError) as error:
        print("error: " + str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
