#!/usr/bin/env python3
"""Publish file-aware skill sources as self-contained OMP skills."""

import argparse
import fnmatch
import json
import re
import sys
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple
from urllib.parse import unquote


GENERATED_MARKER = "<!-- GENERATED BY scripts/build-skills.py; DO NOT EDIT. -->"
SOURCES_DIR = "skill-sources"
FINDINGS_SCHEMAS = Path("guides") / "findings-schemas.json"
FENCE_OPEN = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})(?:[^\n]*)$")
ATX_HEADING = re.compile(r"^[ \t]{0,3}(#{1,6})(?:[ \t]+|$)(.*?)(?:\r?\n)?$")
SETEXT_UNDERLINE = re.compile(r"^[ \t]{0,3}(=+|-+)[ \t]*(?:\r?\n)?$")
MANIFEST_ITEM = re.compile(r"^[ \t]*[-*+][ \t]+\[([^\]]+)\]\(([^()\s]+)\)[ \t]*(?:\r?\n)?$")
URL_SCHEME = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")

SKILL_POINTER = (
    "`skill://{skill}` governs this work: its procedure, its output, and when you are "
    "finished. It overrides this harness's general workflow guidance but never widens "
    "the boundaries below. Re-read it whenever it is not in your context, after any "
    "compaction, and before you finish."
)
COMPLETION_LINE = (
    "You are finished only when the skill's Output section is satisfied. Every ending "
    "it defines is a valid completion, including one that writes nothing or reports no "
    "findings."
)
FALLBACK_LINE = (
    "If `skill://{skill}` cannot be read, stop and report that instead of working from "
    "memory."
)
AGENT_RULES = (
    "skill-has-agent",
    "agent-has-skill",
    "name-matches-file",
    "standard-lines",
    "no-done-when",
    "reviewer-read-only",
    "verbatim-read",
    "output-schema",
    "description-contract",
    "routing-cases",
)


class BuildError(Exception):
    """An invalid source or unsafe output condition."""


@dataclass(frozen=True)
class Heading:
    level: int
    title: str
    slug: str
    start: int
    end: int


@dataclass
class Document:
    path: Path
    relative_path: Path
    lines: List[str]
    headings: List[Heading]


@dataclass(frozen=True)
class SelectedSection:
    document: Document
    start: int
    end: int
    heading_index: Optional[int]

    @property
    def is_whole_document(self) -> bool:
        return self.heading_index is None


@dataclass(frozen=True)
class Bundle:
    source: Path
    output: Path
    name: str
    description: str
    files: Dict[Path, bytes]


@dataclass(frozen=True)
class Agent:
    path: Path
    frontmatter: Dict[str, object]
    body: str
    raw_description: str

def repository_root() -> Path:
    return Path(__file__).resolve().parent.parent


def is_fence_open(line: str) -> Optional[Tuple[str, int]]:
    match = FENCE_OPEN.match(line)
    if not match:
        return None
    marker = match.group(1)
    return marker[0], len(marker)


def is_fence_close(line: str, marker: str, length: int) -> bool:
    return bool(
        re.match(
            r"^[ \t]{0,3}" + re.escape(marker) + r"{" + str(length) + r",}[ \t]*(?:\r?\n)?$",
            line,
        )
    )


def heading_slug(title: str) -> str:
    """Match the simple GitHub-style slugs used by this repository's headings."""
    normalized = unicodedata.normalize("NFKD", title).lower()
    filtered = "".join(
        character
        for character in normalized
        if character.isalnum() or character in " _-" or character.isspace()
    )
    return re.sub(r"\s+", "-", filtered.strip()).strip("-")


def parse_headings(lines: Sequence[str]) -> List[Heading]:
    raw_headings: List[Tuple[int, str, int]] = []
    in_fence = False
    fence_marker = ""
    fence_length = 0

    for index, line in enumerate(lines):
        if in_fence:
            if is_fence_close(line, fence_marker, fence_length):
                in_fence = False
            continue

        opening = is_fence_open(line)
        if opening:
            fence_marker, fence_length = opening
            in_fence = True
            continue

        atx = ATX_HEADING.match(line)
        if atx:
            title = re.sub(r"[ \t]+#+[ \t]*$", "", atx.group(2)).strip()
            raw_headings.append((len(atx.group(1)), title, index))
            continue

        # Setext headings are supported as well. The conservative exclusions avoid
        # treating list items and block quotes followed by a rule as headings.
        if index + 1 < len(lines):
            underline = SETEXT_UNDERLINE.match(lines[index + 1])
            candidate = line.strip()
            if (
                underline
                and candidate
                and not candidate.startswith((">", "- ", "* ", "+ "))
                and not line.startswith(("    ", "\t"))
            ):
                raw_headings.append((1 if underline.group(1)[0] == "=" else 2, candidate, index))

    counts: Dict[str, int] = {}
    headings: List[Heading] = []
    for position, (level, title, start) in enumerate(raw_headings):
        base_slug = heading_slug(title) or "heading-" + str(start + 1)
        occurrence = counts.get(base_slug, 0)
        counts[base_slug] = occurrence + 1
        slug = base_slug if occurrence == 0 else base_slug + "-" + str(occurrence)
        end = len(lines)
        for next_level, _, next_start in raw_headings[position + 1 :]:
            if next_level <= level:
                end = next_start
                break
        headings.append(Heading(level, title, slug, start, end))
    return headings


def is_inside(root: Path, candidate: Path) -> bool:
    try:
        candidate.relative_to(root)
        return True
    except ValueError:
        return False


def load_document(root: Path, path: Path, cache: Dict[Path, Document]) -> Document:
    resolved = path.resolve()
    if not is_inside(root, resolved):
        raise BuildError("local source escapes repository: " + str(path))
    if resolved in cache:
        return cache[resolved]
    if not resolved.is_file():
        raise BuildError("referenced Markdown file does not exist: " + str(path))
    try:
        text = resolved.read_text(encoding="utf-8")
    except UnicodeDecodeError as error:
        raise BuildError("source is not UTF-8: " + str(path)) from error
    document = Document(
        path=resolved,
        relative_path=resolved.relative_to(root),
        lines=text.splitlines(keepends=True),
        headings=parse_headings(text.splitlines(keepends=True)),
    )
    cache[resolved] = document
    return document


def local_path(root: Path, current: Document, path_text: str) -> Path:
    if not path_text:
        return current.path
    decoded = unquote(path_text)
    if "\\" in decoded or "\x00" in decoded:
        raise BuildError("malformed local link in " + str(current.relative_path) + ": " + path_text)
    candidate = Path(decoded)
    if candidate.is_absolute():
        raise BuildError("local link escapes repository in " + str(current.relative_path) + ": " + path_text)
    resolved = (current.path.parent / candidate).resolve()
    if not is_inside(root, resolved):
        raise BuildError("local link escapes repository in " + str(current.relative_path) + ": " + path_text)
    return resolved


def find_manifest(document: Document, title: str, required: bool) -> Optional[Heading]:
    matching = [heading for heading in document.headings if heading.title == title]
    if len(matching) > 1 or (matching and matching[0].level != 2) or (required and not matching):
        raise BuildError(
            str(document.relative_path)
            + (" must contain exactly one" if required else " may contain only one")
            + " level-two '" + title + "' heading"
        )
    return matching[0] if matching else None


def manifest_sections(
    root: Path,
    source: Document,
    manifest: Heading,
    cache: Dict[Path, Document],
) -> List[SelectedSection]:
    selections: List[SelectedSection] = []
    entries = 0
    reference_names = set()
    for index in range(manifest.start + 1, manifest.end):
        line = source.lines[index]
        if not line.strip():
            continue
        item = MANIFEST_ITEM.match(line)
        if not item:
            raise BuildError(
                "malformed " + manifest.title + " entry in "
                + str(source.relative_path)
                + " at line "
                + str(index + 1)
            )
        entries += 1

        target = item.group(2)
        if target.startswith("<") or "?" in target or URL_SCHEME.match(target) or target.startswith("//"):
            raise BuildError(
                manifest.title + " must use a relative local Markdown link in "
                + str(source.relative_path)
                + " at line "
                + str(index + 1)
            )
        path_text, separator, fragment = target.partition("#")
        if not path_text or not path_text.lower().endswith(".md") or (separator and not fragment):
            raise BuildError(
                "malformed " + manifest.title + " link in "
                + str(source.relative_path)
                + " at line "
                + str(index + 1)
            )
        target_path = local_path(root, source, path_text)
        document = load_document(root, target_path, cache)

        heading_index: Optional[int] = None
        if separator:
            requested_slug = unquote(fragment)
            matches = [
                position
                for position, heading in enumerate(document.headings)
                if heading.slug == requested_slug
            ]
            if len(matches) != 1:
                raise BuildError(
                    manifest.title + " fragment does not name a heading in "
                    + str(document.relative_path)
                    + ": #"
                    + fragment
                )
            heading_index = matches[0]
            heading = document.headings[heading_index]
            candidate = SelectedSection(document, heading.start, heading.end, heading_index)
        else:
            candidate = SelectedSection(document, 0, len(document.lines), None)
        if manifest.title == "Reference guidance":
            filename = reference_filename(candidate)
            if filename in reference_names:
                raise BuildError("duplicate reference filename in " + str(source.relative_path) + ": " + filename)
            reference_names.add(filename)

        overlapping = [
            position
            for position, selected in enumerate(selections)
            if selected.document.path == document.path
            and candidate.start < selected.end
            and selected.start < candidate.end
        ]
        if any(
            selections[position].start <= candidate.start
            and candidate.end <= selections[position].end
            and (selections[position].is_whole_document or not candidate.is_whole_document)
            for position in overlapping
        ):
            continue
        if overlapping:
            # Heading ranges are nested: a later parent replaces its children
            # at their first position, retaining the parent's remaining rules.
            insertion = overlapping[0]
            selections = [
                selected for position, selected in enumerate(selections)
                if position not in overlapping
            ]
            selections.insert(insertion, candidate)
        else:
            selections.append(candidate)

    if not entries and manifest.title == "Required guidance":
        raise BuildError(str(source.relative_path) + " must list at least one Required guidance link")
    return selections


def included_sections(selections: Iterable[SelectedSection]) -> Dict[Tuple[Path, Optional[str]], str]:
    sections: Dict[Tuple[Path, Optional[str]], str] = {}
    for selection in selections:
        document = selection.document
        if selection.is_whole_document:
            sections[(document.path, None)] = (
                document.headings[0].title if document.headings else document.relative_path.as_posix()
            )
        for heading in document.headings:
            if selection.start <= heading.start < selection.end:
                sections[(document.path, heading.slug)] = heading.title
    return sections


def reference_filename(selection: SelectedSection) -> str:
    stem = selection.document.path.stem
    if selection.is_whole_document:
        return stem + ".md"
    return stem + "--" + selection.document.headings[selection.heading_index].slug + ".md"


def referenced_sections(
    selections: Iterable[SelectedSection],
) -> Dict[Tuple[Path, Optional[str]], str]:
    sections: Dict[Tuple[Path, Optional[str]], str] = {}
    for selection in selections:
        filename = reference_filename(selection)
        document = selection.document
        if selection.is_whole_document:
            sections[(document.path, None)] = filename
        for heading in document.headings:
            if selection.start <= heading.start < selection.end:
                sections[(document.path, heading.slug)] = filename
    return sections


def split_destination(destination: str) -> str:
    """Return a Markdown link destination without its optional title."""
    value = destination.strip()
    if value.startswith("<"):
        closing = value.find(">")
        if closing == -1:
            return value
        return value[1:closing]
    for index, character in enumerate(value):
        if character.isspace():
            return value[:index]
    return value




def rewrite_destination(
    root: Path,
    current: Document,
    destination: str,
    sections: Dict[Tuple[Path, Optional[str]], str],
    references: Dict[Tuple[Path, Optional[str]], str],
) -> Optional[str]:
    target_text = split_destination(destination)
    if not target_text:
        return None
    if URL_SCHEME.match(target_text) and not target_text.lower().startswith("file:"):
        return None
    if target_text.startswith("//"):
        return None
    if target_text.lower().startswith("file:"):
        raise BuildError("file URL is not allowed in " + str(current.relative_path) + ": " + target_text)

    path_text, separator, fragment = target_text.partition("#")
    target = local_path(root, current, path_text)
    decoded_fragment = unquote(fragment) if separator else None
    section = sections.get((target, decoded_fragment))
    if section:
        return "section:" + section
    filename = references.get((target, decoded_fragment))
    if filename:
        return "reference:" + filename
    reference = target.relative_to(root).as_posix()
    if fragment:
        reference += "#" + fragment
    return "source:" + reference


def rewrite_links_in_line(
    root: Path,
    current: Document,
    line: str,
    sections: Dict[Tuple[Path, Optional[str]], str],
    references: Dict[Tuple[Path, Optional[str]], str],
    skill: str,
    linked: Optional[set] = None,
) -> str:
    result: List[str] = []
    cursor = 0
    while True:
        opening = line.find("[", cursor)
        if opening == -1:
            result.append(line[cursor:])
            break
        close = line.find("]", opening + 1)
        if close == -1 or close + 1 >= len(line) or line[close + 1] != "(":
            result.append(line[cursor : opening + 1])
            cursor = opening + 1
            continue
        depth = 1
        position = close + 2
        while position < len(line) and depth:
            if line[position] == "(":
                depth += 1
            elif line[position] == ")":
                depth -= 1
            position += 1
        if depth:
            result.append(line[cursor : opening + 1])
            cursor = opening + 1
            continue

        start = opening - 1 if opening > 0 and line[opening - 1] == "!" else opening
        label = line[opening + 1 : close]
        destination = line[close + 2 : position - 1]
        rewritten = rewrite_destination(root, current, destination, sections, references)
        result.append(line[cursor:start])
        if rewritten is None:
            result.append(line[start:position])
        elif rewritten.startswith("section:"):
            result.append(label + ' (see included section "' + rewritten[len("section:") :] + '")')
        elif rewritten.startswith("reference:"):
            filename = rewritten[len("reference:") :]
            result.append("[" + label + "](skill://" + skill + "/references/" + filename + ")")
            if linked is not None:
                linked.add(filename)
        else:
            # Local source paths are intentionally text, not broken relative URLs.
            result.append("[" + label + " (source: " + rewritten[len("source:") :] + ")]")
        cursor = position
    return "".join(result)


def rewrite_links(
    root: Path,
    current: Document,
    lines: Sequence[str],
    sections: Dict[Tuple[Path, Optional[str]], str],
    references: Dict[Tuple[Path, Optional[str]], str],
    skill: str,
    linked: Optional[set] = None,
) -> str:
    rewritten: List[str] = []
    in_fence = False
    fence_marker = ""
    fence_length = 0
    eligible = set()
    if linked is not None:
        for heading in parse_headings(lines):
            if heading.level == 2 and heading.title in ("Instructions", "Output"):
                eligible.update(range(heading.start, heading.end))
    for index, line in enumerate(lines):
        if in_fence:
            rewritten.append(line)
            if is_fence_close(line, fence_marker, fence_length):
                in_fence = False
            continue
        opening = is_fence_open(line)
        if opening:
            rewritten.append(line)
            fence_marker, fence_length = opening
            in_fence = True
            continue
        rewritten.append(
            rewrite_links_in_line(
                root, current, line, sections, references, skill,
                linked if index in eligible else None,
            )
        )
    return "".join(rewritten)


def render_section(
    root: Path,
    selection: SelectedSection,
    sections: Dict[Tuple[Path, Optional[str]], str],
    references: Dict[Tuple[Path, Optional[str]], str],
    skill: str,
) -> str:
    document = selection.document
    return rewrite_links(
        root, document, document.lines[selection.start : selection.end],
        sections, references, skill,
    ).strip() + "\n"




def yaml_double_quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def skill_description(source: Document) -> str:
    if not any(
        heading.level == 1 and heading.start == 0 and heading.title
        for heading in source.headings
    ):
        raise BuildError("skill source must begin with an H1 title: " + str(source.relative_path))
    purpose = find_manifest(source, "Purpose", True)
    paragraph: List[str] = []
    for line in source.lines[purpose.start + 1 : purpose.end]:
        if not line.strip():
            if paragraph:
                break
            continue
        paragraph.append(line.strip())
    description = " ".join(paragraph)
    if not description or len(description) > 1024:
        raise BuildError(
            "prompt Purpose first paragraph must be 1–1024 characters: "
            + str(source.relative_path)
        )
    return description


def render_bundle(
    root: Path,
    source: Document,
    inline: Sequence[SelectedSection],
    reference_selections: Sequence[SelectedSection],
    name: str,
    description: str,
) -> Dict[Path, bytes]:
    sections = included_sections(inline)
    references = referenced_sections(reference_selections)
    manifests = [
        heading for heading in source.headings
        if heading.level == 2 and heading.title in ("Required guidance", "Reference guidance")
    ]
    task_lines = [
        line for index, line in enumerate(source.lines)
        if not any(heading.start <= index < heading.end for heading in manifests)
    ]
    linked: set = set()
    task = rewrite_links(root, source, task_lines, sections, references, name, linked).strip()
    guidance = "\n".join(
        render_section(root, selection, sections, references, name).rstrip()
        for selection in inline
    )
    content = "\n".join(
        [
            "---",
            "name: " + name,
            "description: " + yaml_double_quoted(description),
            "hide: true",
            "---",
            GENERATED_MARKER,
            "",
            "## Included guidance",
            "",
            guidance,
            "## Task",
            "",
            task,
            "",
            "## Supply inputs",
            "Provide the target, exact revision label, source material, relevant context, and the action-specific request.",
            "",
        ]
    )
    files = {root / "skills" / name / "SKILL.md": content.encode("utf-8")}
    for selection in reference_selections:
        filename = reference_filename(selection)
        if filename not in linked:
            raise BuildError("reference guidance not linked from Instructions or Output: " + filename)
        heading = (
            "#" + selection.document.headings[selection.heading_index].slug
            if not selection.is_whole_document else ""
        )
        provenance = "Source: " + selection.document.relative_path.as_posix() + heading
        text = (
            GENERATED_MARKER + "\n" + provenance + "\n\n"
            + render_section(root, selection, sections, references, name)
        )
        files[root / "skills" / name / "references" / filename] = text.encode("utf-8")
    return files


def build_bundles(root: Path, only: Optional[Sequence[str]] = None) -> List[Bundle]:
    sources_dir = root / SOURCES_DIR
    if not sources_dir.is_dir():
        raise BuildError("skill source directory does not exist: " + str(sources_dir))
    source_paths = sorted(
        path for path in sources_dir.glob("*.md") if path.name != "README.md" and path.is_file()
    )
    if not source_paths:
        raise BuildError("skill source directory is empty: " + str(sources_dir))
    if only is not None:
        unknown = set(only) - {path.stem for path in source_paths}
        if unknown:
            raise BuildError("unknown skill source: " + ", ".join(sorted(unknown)))
        source_paths = [path for path in source_paths if path.stem in only]

    cache: Dict[Path, Document] = {}
    bundles: List[Bundle] = []
    for path in source_paths:
        source = load_document(root, path, cache)
        required = find_manifest(source, "Required guidance", True)
        reference = find_manifest(source, "Reference guidance", False)
        inline = manifest_sections(root, source, required, cache)
        selected = manifest_sections(root, source, reference, cache) if reference else []
        for selection in selected:
            if any(
                selection.document.path == other.document.path
                and selection.start < other.end and other.start < selection.end
                for other in inline
            ):
                raise BuildError("Required and Reference guidance overlap: " + reference_filename(selection))
        name = path.stem
        description = skill_description(source)
        output = root / "skills" / name / "SKILL.md"
        bundles.append(
            Bundle(path, output, name, description, render_bundle(root, source, inline, selected, name, description))
        )
    return bundles


def parse_agent_scalar(path: Path, line_number: int, value: str) -> str:
    value = value.strip()
    if not value:
        raise BuildError(
            "empty agent frontmatter value at "
            + str(path)
            + ":"
            + str(line_number)
        )
    if value.startswith('"') or value.startswith("'"):
        quote = value[0]
        if len(value) < 2 or value[-1] != quote:
            raise BuildError(
                "invalid quoted agent frontmatter value at "
                + str(path)
                + ":"
                + str(line_number)
            )
        if quote == '"':
            try:
                parsed = json.loads(value)
            except json.JSONDecodeError as error:
                raise BuildError(
                    "invalid quoted agent frontmatter value at "
                    + str(path)
                    + ":"
                    + str(line_number)
                ) from error
            if not isinstance(parsed, str):
                raise BuildError(
                    "agent frontmatter value is not a string at "
                    + str(path)
                    + ":"
                    + str(line_number)
                )
            return parsed
        return value[1:-1].replace("''", "'")
    return value


def parse_agent(path: Path) -> Agent:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise BuildError("agent frontmatter must start with ---: " + str(path))
    try:
        end = lines.index("---", 1)
    except ValueError as error:
        raise BuildError("agent frontmatter is not closed: " + str(path)) from error

    frontmatter: Dict[str, object] = {}
    list_key: Optional[str] = None
    raw_description = ""
    for index, line in enumerate(lines[1:end], start=2):
        if line.startswith("  - "):
            if list_key is None:
                raise BuildError(
                    "agent frontmatter list item has no key at "
                    + str(path)
                    + ":"
                    + str(index)
                )
            value = parse_agent_scalar(path, index, line[4:])
            items = frontmatter[list_key]
            if not isinstance(items, list):
                raise BuildError(
                    "agent frontmatter list has an invalid value at "
                    + str(path)
                    + ":"
                    + str(index)
                )
            items.append(value)
            continue

        match = re.fullmatch(r"([A-Za-z][A-Za-z0-9-]*):(.*)", line)
        if not match:
            raise BuildError(
                "unsupported agent frontmatter at "
                + str(path)
                + ":"
                + str(index)
            )
        key, raw_value = match.groups()
        if key in frontmatter:
            raise BuildError("duplicate agent frontmatter key '" + key + "': " + str(path))
        if key == "description":
            raw_description = raw_value.strip()
        if raw_value.strip():
            frontmatter[key] = parse_agent_scalar(path, index, raw_value)
            list_key = None
        else:
            frontmatter[key] = []
            list_key = key
    return Agent(path, frontmatter, "\n".join(lines[end + 1 :]), raw_description)


def load_agent_exceptions(root: Path) -> Tuple[Dict[str, object], Dict[str, object]]:
    path = root / "agents" / "checks.json"
    if not path.exists():
        return {}, {}
    try:
        configuration = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise BuildError("invalid agent check configuration: " + str(path)) from error
    if not isinstance(configuration, dict):
        raise BuildError("agent check configuration must be an object: " + str(path))
    skills_without_agents = configuration.get("skillsWithoutAgents", {})
    exemptions = configuration.get("exemptions", {})
    if not isinstance(skills_without_agents, dict):
        raise BuildError("skillsWithoutAgents must be an object: " + str(path))
    if not isinstance(exemptions, dict):
        raise BuildError("exemptions must be an object: " + str(path))
    return skills_without_agents, exemptions


def agent_list(agent: Agent, key: str) -> List[str]:
    value = agent.frontmatter.get(key)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        return []
    return value


def agent_name(agent: Agent) -> str:
    value = agent.frontmatter.get("name")
    return value if isinstance(value, str) else ""


def load_findings_schemas(root: Path) -> Dict[str, Tuple[List[str], Dict[str, object]]]:
    path = root / FINDINGS_SCHEMAS
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise BuildError("invalid findings schemas: " + str(path)) from error
    families = data.get("families") if isinstance(data, dict) else None
    if not isinstance(families, dict):
        raise BuildError("findings schemas must contain a families object: " + str(path))
    result: Dict[str, Tuple[List[str], Dict[str, object]]] = {}
    for family, entry in families.items():
        globs = entry.get("agents") if isinstance(entry, dict) else None
        schema = entry.get("schema") if isinstance(entry, dict) else None
        if (
            not isinstance(globs, list)
            or not globs
            or not all(isinstance(glob, str) and glob for glob in globs)
            or not isinstance(schema, dict)
        ):
            raise BuildError("findings schema family needs agents and schema: " + str(family))
        result[str(family)] = (globs, schema)
    return result


def output_line(schema: Dict[str, object]) -> str:
    return "output: " + json.dumps(
        schema, sort_keys=True, separators=(", ", ": "), ensure_ascii=False
    )


def agent_family(
    name: str, families: Dict[str, Tuple[List[str], Dict[str, object]]]
) -> Optional[str]:
    matches = [
        family
        for family, (globs, _) in families.items()
        if any(fnmatch.fnmatchcase(name, glob) for glob in globs)
    ]
    if len(matches) > 1:
        raise BuildError(
            "agent matches several findings schema families: " + name + ": " + ", ".join(matches)
        )
    return matches[0] if matches else None


def synced_agent_text(path: Path, line: str) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    end = lines.index("---", 1)
    for index in range(1, end):
        if lines[index].startswith("output:"):
            lines[index] = line
            break
    else:
        insert_at = end
        for index in range(1, end):
            if lines[index].startswith("tools:"):
                insert_at = index + 1
        lines.insert(insert_at, line)
    return "\n".join(lines) + "\n"


def sync_agent_outputs(root: Path, write: bool) -> List[Path]:
    """Write each review family's schema into its agents' `output:` frontmatter."""
    families = load_findings_schemas(root)
    agents_dir = root / "agents"
    if not families or not agents_dir.is_dir():
        return []
    _, exemptions = load_agent_exceptions(root)
    changed: List[Path] = []
    for path in sorted(agents_dir.glob("*.md")):
        name = agent_name(parse_agent(path))
        family = agent_family(name, families)
        if family is None:
            continue
        rules = exemptions.get(name)
        if isinstance(rules, dict) and "output-schema" in rules:
            continue
        expected = synced_agent_text(path, output_line(families[family][1]))
        if path.read_text(encoding="utf-8") != expected:
            changed.append(path)
            if write:
                path.write_text(expected, encoding="utf-8")
    return changed


def check_agents(root: Path) -> List[str]:
    agents_dir = root / "agents"
    agents = (
        [parse_agent(path) for path in sorted(agents_dir.glob("*.md"))]
        if agents_dir.is_dir()
        else []
    )
    skill_names = {
        path.parent.name
        for path in (root / "skills").glob("*/SKILL.md")
        if path.is_file()
    }
    agents_by_name = {
        agent_name(agent): agent for agent in agents if agent_name(agent)
    }
    skills_without_agents, configured_exemptions = load_agent_exceptions(root)
    routing_path = agents_dir / "routing-cases.json"
    try:
        routing = json.loads(routing_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        routing = None
    violations: List[str] = []
    valid_skill_exceptions = set()
    valid_exemptions = set()

    for skill, reason in sorted(skills_without_agents.items()):
        if skill not in skill_names:
            violations.append(
                "skill " + skill + ": skillsWithoutAgents: unknown skill"
            )
        if not isinstance(reason, str) or not reason.strip():
            violations.append(
                "skill "
                + skill
                + ": skillsWithoutAgents: reason must be a non-empty string"
            )
        if skill in skill_names and isinstance(reason, str) and reason.strip():
            valid_skill_exceptions.add(skill)

    for name, exemptions in sorted(configured_exemptions.items()):
        agent = agents_by_name.get(name)
        label = agent.path.name if agent is not None else name
        if agent is None:
            violations.append("agent " + label + ": exemptions: unknown agent")
        if not isinstance(exemptions, dict):
            raise BuildError("agent exemptions must be an object: " + name)
        for rule, reason in sorted(exemptions.items()):
            if rule not in AGENT_RULES:
                violations.append("agent " + label + ": " + rule + ": unknown rule")
            if not isinstance(reason, str) or not reason.strip():
                violations.append(
                    "agent "
                    + label
                    + ": "
                    + rule
                    + ": reason must be a non-empty string"
                )
            if (
                agent is not None
                and rule in AGENT_RULES
                and isinstance(reason, str)
                and reason.strip()
            ):
                valid_exemptions.add((name, rule))

    def exempt(agent: Agent, rule: str) -> bool:
        return (agent_name(agent), rule) in valid_exemptions

    agents_for_skill: Dict[str, List[Agent]] = {}
    for agent in agents:
        for skill in agent_list(agent, "autoloadSkills"):
            agents_for_skill.setdefault(skill, []).append(agent)

    for skill in sorted(skill_names):
        if skill in valid_skill_exceptions:
            continue
        count = len(agents_for_skill.get(skill, []))
        if count != 1:
            violations.append(
                "skill "
                + skill
                + ": skill-has-agent: expected exactly one agent, found "
                + str(count)
            )
    routing_errors: Dict[str, List[str]] = {agent_name(agent): [] for agent in agents}
    if not isinstance(routing, dict):
        for agent in agents:
            routing_errors[agent_name(agent)].append("agents/routing-cases.json must exist and parse as an object")
    else:
        for extra in sorted(routing.keys() - agents_by_name.keys()):
            violations.append("agent " + str(extra) + ": routing-cases: unknown agent")
        positive_seen = set()
        for agent in agents:
            name = agent_name(agent)
            entry = routing.get(name)
            errors = routing_errors[name]
            if not isinstance(entry, dict):
                errors.append("missing agent entry")
                continue
            positives = entry.get("positive")
            negatives = entry.get("negative")
            if not isinstance(positives, list) or len(positives) < 3 or not all(
                isinstance(request, str) and request.strip() for request in positives
            ):
                errors.append("positive must have at least three request strings")
            if not isinstance(negatives, list) or len(negatives) < 2:
                errors.append("negative must have at least two cases")
            for request in positives if isinstance(positives, list) else []:
                if not isinstance(request, str):
                    continue
                if request in positive_seen:
                    errors.append("duplicate positive request: " + request)
                positive_seen.add(request)
            sibling = False
            for case in negatives if isinstance(negatives, list) else []:
                if not isinstance(case, dict) or not isinstance(case.get("request"), str) or not case["request"].strip() or "expected" not in case:
                    errors.append("negative case must contain a request and expected")
                    continue
                expected = case["expected"]
                if expected is not None and (
                    not isinstance(expected, str) or expected not in agents_by_name or expected == name
                ):
                    errors.append("negative expected must name another agent or null")
                if isinstance(expected, str) and expected.startswith("review-doc-") and expected in agents_by_name and expected != name:
                    sibling = True
            if name.startswith("review-doc-") and not sibling:
                errors.append("review-doc negative must expect a review-doc sibling")
            requests = (
                [request for request in positives if isinstance(request, str)]
                if isinstance(positives, list) else []
            ) + (
                [case["request"] for case in negatives if isinstance(case, dict) and isinstance(case.get("request"), str)]
                if isinstance(negatives, list) else []
            )
            if any(other.casefold() in request.casefold() for request in requests for other in agents_by_name):
                errors.append("request must not contain an agent name")

    families = load_findings_schemas(root)
    for agent in agents:
        name = agent_name(agent)
        skills = agent_list(agent, "autoloadSkills")
        label = agent.path.name
        description = agent.frontmatter.get("description")
        if not exempt(agent, "description-contract") and (
            not agent.raw_description.startswith('"')
            or not agent.raw_description.endswith('"')
            or not isinstance(description, str)
            or not 1 <= len(description) <= 400
            or "\n" in description
            or "Use when" not in description
            or "Not for" not in description
            or re.search(r"\b(?:MUST|ALWAYS|NEVER|CRITICAL)\b", description)
        ):
            violations.append(
                "agent " + label + ": description-contract: description must be one double-quoted line, ≤400 characters, contain Use when and Not for, and avoid directive words"
            )
        if routing_errors.get(name) and not exempt(agent, "routing-cases"):
            for reason in routing_errors[name]:
                violations.append("agent " + label + ": routing-cases: " + reason)
        if not exempt(agent, "agent-has-skill") and (
            len(skills) != 1 or skills[0] not in skill_names
        ):
            violations.append(
                "agent "
                + label
                + ": agent-has-skill: autoloadSkills must name exactly one existing skill"
            )
        if not exempt(agent, "name-matches-file") and name != agent.path.stem:
            violations.append(
                "agent "
                + label
                + ": name-matches-file: name '"
                + name
                + "' does not match filename"
            )
        if not exempt(agent, "standard-lines"):
            if len(skills) == 1:
                standard_lines = (
                    SKILL_POINTER.format(skill=skills[0]),
                    COMPLETION_LINE,
                    FALLBACK_LINE.format(skill=skills[0]),
                )
                body_lines = set(agent.body.splitlines())
                missing = [line for line in standard_lines if line not in body_lines]
            else:
                missing = ["standard lines require exactly one autoloaded skill"]
            if missing:
                violations.append(
                    "agent "
                    + label
                    + ": standard-lines: missing "
                    + "; ".join(missing)
                )
        if not exempt(agent, "no-done-when") and "You are done when" in agent.body:
            violations.append(
                "agent "
                + label
                + ": no-done-when: body contains 'You are done when'"
            )
        if (
            name.startswith("review-")
            and not exempt(agent, "reviewer-read-only")
        ):
            tools_value = agent.frontmatter.get("tools")
            if isinstance(tools_value, str):
                tools = {tool.strip() for tool in tools_value.split(",")}
            elif isinstance(tools_value, list):
                tools = {str(tool).strip() for tool in tools_value}
            else:
                tools = set()
            forbidden = sorted(tools.intersection({"edit", "write", "bash"}))
            if forbidden:
                violations.append(
                    "agent "
                    + label
                    + ": reviewer-read-only: forbidden tools: "
                    + ", ".join(forbidden)
                )
        if not exempt(agent, "verbatim-read") and agent.frontmatter.get("read-summarize") != "false":
            violations.append(
                "agent " + label + ": verbatim-read: frontmatter must set read-summarize: false"
            )
        family = agent_family(name, families)
        if family is not None and not exempt(agent, "output-schema"):
            expected = output_line(families[family][1])
            value = agent.frontmatter.get("output")
            if not isinstance(value, str) or "output: " + value != expected:
                violations.append(
                    "agent " + label + ": output-schema: output must match the "
                    + family + " schema in " + str(FINDINGS_SCHEMAS) + " (run the build)"
                )
    return violations


def is_our_bundle(content: bytes) -> bool:
    marker = GENERATED_MARKER.encode("utf-8")
    return marker in content.splitlines()


def inspect_outputs(
    root: Path, bundles: Sequence[Bundle], scan_stale: bool = True
) -> Tuple[List[Path], List[Path]]:
    skills_dir = root / "skills"
    expected = {path: content for bundle in bundles for path, content in bundle.files.items()}
    changed: List[Path] = []
    stale: List[Path] = []

    if skills_dir.is_symlink():
        raise BuildError("skills path must not be a symbolic link: " + str(skills_dir))
    if skills_dir.exists() and not skills_dir.is_dir():
        raise BuildError("skills path is not a directory: " + str(skills_dir))
    for path, content in expected.items():
        for directory in (path.parent.parent, path.parent):
            if directory.is_symlink():
                raise BuildError("skill path must not be a symbolic link: " + str(directory))
            if directory.exists() and not directory.is_dir():
                raise BuildError("skill path is not a directory: " + str(directory))
        if path.is_symlink():
            raise BuildError("skill output must not be a symbolic link: " + str(path))
        if not path.exists():
            changed.append(path)
            continue
        if not path.is_file():
            raise BuildError("skill output is not a file: " + str(path))
        existing = path.read_bytes()
        if not is_our_bundle(existing):
            raise BuildError("refusing to overwrite unrecognized file: " + str(path))
        if existing != content:
            changed.append(path)

    if scan_stale and skills_dir.is_dir():
        for path in sorted(skills_dir.rglob("*")):
            if path.is_symlink():
                raise BuildError("skill path must not be a symbolic link: " + str(path))
            if path.is_dir():
                continue
            if not path.is_file():
                raise BuildError("skill output is not a file: " + str(path))
            if not is_our_bundle(path.read_bytes()):
                raise BuildError("refusing to overwrite unrecognized file: " + str(path))
            if path not in expected:
                stale.append(path)

    return changed, stale


def skill_size(bundle: Bundle) -> Tuple[int, int]:
    text = bundle.files[bundle.output].decode("utf-8")
    return len(text.splitlines()), len(text.split())


def publish(root: Path, check: bool, only: Optional[Sequence[str]] = None) -> int:
    bundles = build_bundles(root, only)
    changed, stale = inspect_outputs(root, bundles, scan_stale=only is None)
    oversize = []
    for bundle in bundles:
        lines, words = skill_size(bundle)
        if lines > 500 or words > 3800:
            oversize.append(
                "oversize: " + str(bundle.output.relative_to(root))
                + " (" + str(lines) + " lines, " + str(words) + " words; limit 500/3800)"
            )
    if check:
        violations = check_agents(root) if only is None else []
        for path in changed:
            print("out of date: " + str(path.relative_to(root)), file=sys.stderr)
        for path in stale:
            print("stale: " + str(path.relative_to(root)), file=sys.stderr)
        for message in oversize:
            print(message, file=sys.stderr)
        for violation in violations:
            print(violation, file=sys.stderr)
        if changed or stale or oversize or violations:
            return 1
        print("generated skills: current")
        return 0

    if oversize:
        for message in oversize:
            print(message, file=sys.stderr)
        return 1
    synced = sync_agent_outputs(root, write=True) if only is None else []
    for path in synced:
        print("agent output schema: " + str(path.relative_to(root)))
    expected = {path: content for bundle in bundles for path, content in bundle.files.items()}
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected[path])
    for path in stale:
        path.unlink()
        parent = path.parent
        while parent != root / "skills" and parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent
    print("generated skills: " + str(len(changed) + len(stale)) + " changed")
    print("name lines words references")
    for bundle in bundles:
        lines, words = skill_size(bundle)
        print(bundle.name, lines, words, len(bundle.files) - 1)
    return 0


def parse_arguments(arguments: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated OMP skills are not current")
    parser.add_argument("--only", nargs="+", metavar="NAME", help="build only these skill sources")
    return parser.parse_args(arguments)


def main(arguments: Optional[Sequence[str]] = None) -> int:
    try:
        options = parse_arguments(arguments)
        return publish(repository_root(), options.check, options.only)
    except (BuildError, OSError) as error:
        print("error: " + str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
