#!/usr/bin/env python3
"""Locate one Playbook agent's runs in OMP session transcripts and emit pointers as JSON.

Output points into transcripts by path and 1-based line number; it copies no transcript
content except `Friction:` lines from each run's final report.
"""

import argparse
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


PLAYBOOK_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SESSIONS = "~/.omp/agent/sessions"
GENERATED_MARKER = "<!-- GENERATED BY scripts/build-skills.py; DO NOT EDIT. -->"
FRICTION_LINE = re.compile(r"^\s*(?:[-*]\s+)?\**Friction:\**\s*(.+?)\s*$")
FRICTION_TEXT_LIMIT = 500
INIT_SCAN_LINES = 20


class UsageError(Exception):
    pass


def parse_bound(value: str, end_of_day: bool) -> datetime.datetime:
    try:
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
            day = datetime.date.fromisoformat(value)
            moment = datetime.datetime.combine(
                day, datetime.time.max if end_of_day else datetime.time.min)
            return moment.replace(tzinfo=datetime.timezone.utc)
        moment = datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        raise UsageError(f"invalid date or timestamp: {value!r}; use YYYY-MM-DD or ISO 8601") from None
    if moment.tzinfo is None:
        moment = moment.replace(tzinfo=datetime.timezone.utc)
    return moment


def parse_timestamp(value: object) -> Optional[datetime.datetime]:
    if not isinstance(value, str):
        return None
    try:
        return datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def playbook_agents() -> List[str]:
    return sorted(path.stem for path in (PLAYBOOK_ROOT / "agents").glob("*.md"))


def read_lines(path: Path) -> List[str]:
    with path.open(encoding="utf-8", errors="replace") as handle:
        return handle.read().splitlines()


def parse_entry(line: str) -> Optional[dict]:
    try:
        entry = json.loads(line)
    except ValueError:
        return None
    return entry if isinstance(entry, dict) else None


def session_cwd(main: Path) -> Optional[str]:
    with main.open(encoding="utf-8", errors="replace") as handle:
        for _, line in zip(range(INIT_SCAN_LINES), handle):
            entry = parse_entry(line)
            if entry and entry.get("type") == "session":
                cwd = entry.get("cwd")
                return cwd if isinstance(cwd, str) else None
    return None


def find_init(transcript: Path) -> Optional[Tuple[int, dict]]:
    with transcript.open(encoding="utf-8", errors="replace") as handle:
        for number, line in zip(range(1, INIT_SCAN_LINES + 1), handle):
            if '"session_init"' not in line:
                continue
            entry = parse_entry(line)
            if entry and entry.get("type") == "session_init":
                return number, entry
    return None


def message(entry: Optional[dict]) -> dict:
    value = entry.get("message") if entry else None
    return value if isinstance(value, dict) else {}


def text_parts(content: object) -> List[str]:
    if isinstance(content, str):
        return [content]
    if not isinstance(content, list):
        return []
    return [part["text"] for part in content
            if isinstance(part, dict) and part.get("type") == "text" and isinstance(part.get("text"), str)]


def friction_lines(path: Path, line: int, texts: List[str]) -> List[dict]:
    found = []
    for text in texts:
        for raw in text.splitlines():
            match = FRICTION_LINE.match(raw)
            if match:
                found.append({"path": str(path), "line": line,
                              "text": match.group(1)[:FRICTION_TEXT_LIMIT]})
    return found


def inspect_run(transcript: Path) -> dict:
    lines = read_lines(transcript)
    skill_read_line = task_line = final_line = None
    end_reason = None
    final_texts: List[str] = []
    for number, line in enumerate(lines, 1):
        if task_line is None and '"user"' in line and message(parse_entry(line)).get("role") == "user":
            task_line = number
        if skill_read_line is None and GENERATED_MARKER in line:
            body = message(parse_entry(line))
            if body.get("role") == "toolResult" and body.get("toolName") == "read":
                skill_read_line = number
        if '"assistant"' in line:
            body = message(parse_entry(line))
            if body.get("role") != "assistant":
                continue
            end_reason = body.get("stopReason") if isinstance(body.get("stopReason"), str) else None
            texts = [text for text in text_parts(body.get("content")) if text.strip()]
            if texts:
                final_line, final_texts = number, texts
    output = transcript.with_suffix(".md")
    if output.is_file():
        output_lines = read_lines(output)
        friction = [item for number, text in enumerate(output_lines, 1)
                    for item in friction_lines(output, number, [text])]
    else:
        output = None
        friction = friction_lines(transcript, final_line, final_texts) if final_line else []
    return {
        "lines": len(lines),
        "taskLine": task_line,
        "skillReadLine": skill_read_line,
        "finalLine": final_line,
        "endReason": end_reason,
        "output": str(output) if output else None,
        "friction": friction,
    }


def is_dispatch(entry: dict, name: str) -> bool:
    body = message(entry)
    if body.get("role") != "assistant" or not isinstance(body.get("content"), list):
        return False
    for part in body["content"]:
        if not isinstance(part, dict) or part.get("type") != "toolCall" or part.get("name") != "task":
            continue
        tasks = part.get("arguments", {}).get("tasks") if isinstance(part.get("arguments"), dict) else None
        if isinstance(tasks, list) and any(isinstance(task, dict) and task.get("name") == name for task in tasks):
            return True
    return False


def inspect_parent(lines: List[str], name: str) -> dict:
    pattern = re.compile(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])")
    delivered = re.compile(r'task-result id=\\?"' + re.escape(name) + r'\\?"')
    dispatch = result = reply = None
    for number, line in enumerate(lines, 1):
        if dispatch is None:
            if pattern.search(line):
                entry = parse_entry(line)
                if entry and is_dispatch(entry, name):
                    dispatch = number
            continue
        if result is None:
            if delivered.search(line):
                result = number
            continue
        if '"user"' in line and message(parse_entry(line)).get("role") == "user":
            reply = number
            break
    return {"dispatchLine": dispatch, "resultLine": result, "developerReplyLine": reply}


def playbook_commit_before(moment: datetime.datetime) -> Optional[str]:
    completed = subprocess.run(
        ["git", "--no-optional-locks", "-C", str(PLAYBOOK_ROOT), "log", "-1", "--format=%H",
         "--before=" + moment.isoformat()],
        capture_output=True, text=True, check=False)
    commit = completed.stdout.strip()
    return commit if completed.returncode == 0 and commit else None


def collect(agent: str, since: datetime.datetime, until: Optional[datetime.datetime],
            project: Optional[str], sessions: Path) -> List[dict]:
    runs = []
    parents: Dict[Path, List[str]] = {}
    for main in sorted(sessions.glob("*/*.jsonl")):
        folder = main.with_suffix("")
        if not folder.is_dir():
            continue
        cwd = session_cwd(main)
        if project is not None and (cwd is None or (cwd != project and not cwd.startswith(project + "/"))):
            continue
        for transcript in sorted(folder.rglob("*.jsonl")):
            found = find_init(transcript)
            if found is None:
                continue
            init_line, init = found
            started = parse_timestamp(init.get("timestamp"))
            if (init.get("agent") != agent or started is None or started < since
                    or (until is not None and started > until)):
                continue
            parent = transcript.parent.with_suffix(".jsonl")
            name = transcript.stem
            if parent != main:
                name = name.split(".")[-1]
            if parent.is_file() and parent not in parents:
                parents[parent] = read_lines(parent)
            run = inspect_run(transcript)
            runs.append({
                "run": name,
                "startedAt": init["timestamp"],
                "project": cwd,
                "model": init.get("resolvedModel"),
                "playbookCommitBefore": playbook_commit_before(started),
                "transcript": {
                    "path": str(transcript),
                    "lines": run["lines"],
                    "initLine": init_line,
                    "taskLine": run["taskLine"],
                    "skillReadLine": run["skillReadLine"],
                    "finalLine": run["finalLine"],
                    "endReason": run["endReason"],
                },
                "output": run["output"],
                "friction": run["friction"],
                "parent": {"path": str(parent), **inspect_parent(parents.get(parent, []), name)},
            })
    runs.sort(key=lambda item: (item["startedAt"], item["transcript"]["path"]))
    return runs


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--agent", required=True, help="Playbook agent name, for example review-prompt-agent.")
    parser.add_argument("--since", required=True, help="Inclusive start: YYYY-MM-DD (UTC day) or ISO 8601.")
    parser.add_argument("--until", help="Inclusive end: YYYY-MM-DD (UTC day) or ISO 8601. Default: no end.")
    parser.add_argument("--project", help="Absolute project path; keeps sessions whose working directory is it or inside it.")
    parser.add_argument("--sessions", default=DEFAULT_SESSIONS,
                        help=f"OMP sessions directory. Default: {DEFAULT_SESSIONS}.")
    args = parser.parse_args(argv)
    try:
        agents = playbook_agents()
        if args.agent not in agents:
            raise UsageError(f"unknown Playbook agent {args.agent!r}; expected one of: {', '.join(agents)}")
        since = parse_bound(args.since, end_of_day=False)
        until = parse_bound(args.until, end_of_day=True) if args.until else None
        if until is not None and since > until:
            raise UsageError("--since must not be after --until")
        project = None
        if args.project:
            if not Path(args.project).is_absolute():
                raise UsageError(f"--project must be an absolute path: {args.project!r}")
            project = args.project.rstrip("/") or "/"
        sessions = Path(args.sessions).expanduser()
        if not sessions.is_dir():
            raise UsageError(f"sessions directory not found: {sessions}")
        runs = collect(args.agent, since, until, project, sessions)
    except UsageError as error:
        print(f"collect-agent-runs: {error}", file=sys.stderr)
        return 1
    json.dump({
        "agent": args.agent,
        "since": since.isoformat(),
        "until": until.isoformat() if until else None,
        "project": project,
        "sessions": str(sessions),
        "runs": runs,
    }, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
